export const subTypes = [
    "Inexperienced",
    "Illusion",
    "of Kuyo",
    "Wanderer",
    "Accomplished",
    "Vermillion Flame",
    "Godly Golden Winged Bird",
    "Hero of Akaeda",
    "Unmatched Steel",
    "Brave Red Capote",
    "Noble Demon King",
    "Blasted Road",
    "Agent of God",
    "Princess of Pure Madness",
    "Seven Stars of Death",
    "Agent of God",
    "Nimble",
    "Joyful",
    "Prideful",
    "Wrathful",
    "Lustful",
    "Magician",
    "Mystic",
    "Bringer of Aging",
    "Pleasure Bringer",
    "Huntress",
    "Heaven-Piercing",
    "Gojo Bridge",
    "of Assault",
    "Shana",
    "Hassou Tobi",
    "Horse",
    "Shining",
    "Premature",
    "Accomplished",
    "Deformed",
    "Lucky",
    "Lost",
    "Late Bloomer",
    "Mirror",
    "Traditional",
    "Kissy",
    "Leader",
    "Rainbow of Victory",
    "Stray",
    "Crisis",
    "Nightmare",
    "Creator",
    "Demi-Fiend's",
    "Stormy",
    "Blizzard",
    "Inferno",
    "Asura",
    "Three-Headed",
    "of the Sea"
]

export const racesLaw: string[] = [
    "Avian",
    "Demon God",
    "Divine",
    "Earth Element",
    "Entity",
    "Evil Demon",
    "Goddess",
    "Heavenly God",
    "Raptor",
    "Seraph",
    "Vile",
    "Wild Bird",
    "Yoma"
]

export const racesNeutral: string[] = [
    "Beast",
    "Demigod",
    "Dragon King",
    "Element",
    "Fairy",
    "Fiend",
    "Godly Beast",
    "Holy Beast",
    "Nocturne",
    "Reaper",
    "Wilder",
    "Sacred Soul"
]

export const racesChaos: string[] = [
    "Brute",
    "Destroyer",
    "Dragon",
    "Earth Mother",
    "Evil Dragon",
    "Fallen",
    "Femme",
    "Foul",
    "Guardian",
    "Haunt",
    "Nation Ruler",
    "Tyrant"
]